[tool.poetry]
name = "tom-base"
version = "2.12.0"
description = "The base Django project for a Target and Observation Manager"
authors = ["TOM Toolkit Project <tomtoolkit@lco.global>", "Lindy Lindstrom <llindstrom@lco.global>", "Joey Chatelain <jchatelain@lco.global>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "tom_base"}]

[tool.poetry.dependencies]
python = "^3.8"
astroquery = "^0.4.2"
astroplan = ">=0.8,<1.0"
astropy = ">=4.1"
beautifulsoup4 = ">=4.9,<5.0"
django = ">=3.1,<5.0"
djangorestframework = ">=3.12,<4.0"
django-bootstrap4 = "^3"
django-contrib-comments = ">=2.0,<3.0"
django-crispy-forms = ">=1.11,<2.0"
django-extensions = ">=3.1,<4.0"
django-filter = ">=21,<23"
django-gravatar2 = ">=1.4,<2.0"
django-guardian = ">=2.3,<3.0"
fits2image = ">=0.4.2"
markdown = ">=3.4"
numpy = ">=1.20,<2.0"
pillow = ">=9.2,<10.0"
plotly = ">=5.0,<6.0"
python-dateutil = ">=2.8,<3.0"
requests = ">=2.25,<3.0"
specutils = ">=1.8,<2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
